- name: variables
  hosts: local
  connection: local
  vars: #play level variable or global variables
    COURSE: "Devops with AWS"
    DURATION: 120hrs
    TRAINER: Ramana
  tasks:
  - name: print the variables
    ansible.builtin.debug;
      msg: "course is {{ COURSE }} and the duration is {{ DURATION }} trained by {{ TRAINER}}"