- name: variables usinng inventory
  hosts: local
  connection: local
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{ COURSE }} and the duration is {{ DURATION }} trained by {{ TRAINER }}"

#give variables in inventory.ini file as
# [local:vars]
#COURSE: Ansible
#DURATION: 100Hrs
#TRAINER: Venkat
